
export const LOAD_STUDENTS = "LOAD_STUDENTS";

export const ADD_STUDENT = "ADD_STUDENT";

export const UPDATE_STUDENT = "UPDATE_STUDENT";

export const DELETE_STUDENT = "DELETE_STUDENT";

export const SELECT_STUDENT = "SELECT_STUDENT";

export const UNSELECT_STUDENT = "UNSELECT_STUDENT";

